spring:
  profiles:
    default: dev # application-test.yaml을 기본으로 사용
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    # /static/ 으로 시작하는 요청에 대해 정적 파일 서빙
    static-path-pattern: /static/**
  web:
    resources:
      # 정적 파일 탐색 장소
      static-locations: file:media/,classpath:/static
logging:
  level:
    root: info

